---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/light-stemcell-builder}
#  type: registry-image
#  source: { repository: golang, tag: 1.19.2 }
#  type: docker-image
#  source: {repository: boshcpi/light-stemcell-builder}

inputs:
  - name: builder-src
  - name: input-stemcell
  - name: aliyun-cli

outputs:
  - name: light-stemcell
  - name: notification

run:
  path: builder-src/ci/tasks/build.sh
params:
  bosh_io_bucket_name:   "bosh-alicloud-light-stemcells-eu"
  bosh_io_bucket_region: "eu-central-1"
  image_description:     ""
  image_region:          ""
  image_access_key:      ""
  image_secret_key:      ""
  image_bucket_name:     "bosh-alicloud-light-stemcells-eu"
  image_destinations:    ""
